### PR TITLE
Record events when failing over

### LINKED ISSUE #73: Emit kubernetes events when a failover status changes
When changing a traffic split, we should publish a Kubernetes event for the trafficsplit indicating whether its status: _primary_, _failover_ or _empty_

### PR DESCRIPTION
**Pull request by adleong**
Fixes #73 

We emit a kubernetes event whenever a failover is triggered and we watch the TrafficSplit. 

Examples:

```
5m16s       Normal   Failover            trafficsplit/split          trafficsplit/split switching traffic to primary
10m         Normal   Failover            trafficsplit/split          trafficsplit/split failing over to fallbacks
```

### CODE REVIEW

File: controller/src/traffic_split.rs [hunk 1]
```diff
@@ -166,17 +173,44 @@ async fn patch(
...
+            type_: events::EventType::Normal,
+            reason: FAILOVER.to_string(),
+            note: Some(description),
+            action: FAILOVER.to_string(),
+            secondary: None,
+        })
+        .await
+    {
+        tracing::error!(%error, "failed to record event");
+    }
```
Comment (olix0r) [inline controller/src/traffic_split.rs:208]: perhaps worth being in its own `async fn`? kind of decoupled from the patching logic...

Also, would it be better to emit this event after patching succeeds so that we do't have the possibility of false-positives?

**Review by olix0r — COMMENTED** [review]
How might we test this?

File: controller/src/traffic_split.rs [hunk 2]
```diff
@@ -166,17 +173,44 @@ async fn patch(
...
-    let api = Api::<TrafficSplit>::namespaced(client, &namespace);
-    let name = target.name;
+    let namespace = target.namespace.as_ref().expect("namespace must be set");
+    let api = Api::<TrafficSplit>::namespaced(client.clone(), namespace);
+    let name = &target.name;
     tracing::debug!("patching trafficsplit");
 
-    let patch = mk_patch(&name, &backends);
+    let event_reporter = events::Reporter {
+        controller: "linkerd-failover".to_string(),
```
Comment (kleimkuhler) [inline controller/src/traffic_split.rs:188]: If we're using the `const FAILOVER` above maybe it makes sense to use a constant for this as well?

**Review by kleimkuhler — COMMENTED** [review]
Overall this looks good and works well for me! I agree about Oliver's comment above where it may make sense to move some of the event recording logic into its own function — separate from `fn patch`.

For testing I created two services: `nginx-1` and `nginx-2`. There is a traffic split which uses `nginx-1` as the primary service.

I ran the controller locally and edited `nginx-1` deployment to have `0` replicas which causes a failover to happen. I saw the events in `kubectl get events` as expected.

<details>
<summary>ts-apps.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
spec:
  selector:
    matchLabels:
      app: nginx-1
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  selector:
    app: nginx-1
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  selector:
    matchLabels:
      app: nginx-2
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
spec:
  selector:
    app: nginx-2
  ports:
  - port: 80
---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: nginx-ts
  labels:
    failover.linkerd.io/controlled-by: linkerd-failover
  annotations:
    failover.linkerd.io/primary-service: nginx-1
spec:
  service: nginx-1
  backends:
  - service: nginx-1
    weight: 1
  - service: nginx-2
    weight: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: [ "sleep", "infinity" ]
```
</details>

**Comment by adleong** [comment]
Gonna defer testing to a later branch

**Review by kleimkuhler — APPROVED** [review]
👍
